swagger: '2.0'
info:
  version: v1
  title: Car finder API
host: carfinderai.appspot.com
paths:
  /brands:
    get:
      tags:
        - Cars
      operationId: GetAllBrands
      consumes: []
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Brand'
  /brands/models:
    get:
      tags:
        - Cars
      operationId: GetModelsForBrand
      consumes: []
      produces:
        - application/json
      parameters:
        - name: brandHttpPath
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/CarModel'
  /brands/models/cars:
    get:
      tags:
        - Cars
      operationId: GetCarsForModel
      consumes: []
      produces:
        - application/json
      parameters:
        - name: modelHttpPath
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Model'
  /api/Cars:
    get:
      tags:
        - Cars
      operationId: GetCars
      consumes: []
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            uniqueItems: false
            type: array
            items:
              $ref: '#/definitions/Brand'
definitions:
  Brand:
    type: object
    properties:
      httpPath:
        type: string
      brandName:
        type: string
      models:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/CarModel'
  CarModel:
    type: object
    properties:
      httpPath:
        type: string
      modelName:
        type: string
      models:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Model'
  Model:
    type: object
    properties:
      httpPath:
        type: string
      modelName:
        type: string
      carImage:
        type: string
      cars:
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Car'
  Car:
    type: object
    properties:
      name:
        type: string
      avitoUri:
        type: string
      characteristics:
        $ref: '#/definitions/Сharacteristics'
  Сharacteristics:
    type: object
    properties:
      manufactureStartDate:
        type: string
      manufactureEndDate:
        type: string
      lowPrice:
        format: double
        type: number
      highPrice:
        format: double
        type: number
      transmission:
        type: string
      bodyType:
        format: int32
        enum:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
        type: integer
